### ISSUE TITLE
Migration locations

### ISSUE THREAD

**Issue by ChambreNoire** [agileek/java-checksum-flyway-maven-plugin#1]
Hi,
Any chance of multiple migration locations at some point?
Cheers

**Comment by MichaelBitard** [comment]
Hi,

I'm working on it, probably will be able to release later tonight.

Michaël

**Comment by MichaelBitard** [comment]
I just released it, it could take some time to propagate to maven central.

Feel free to open a new issue/start a pull request if something is wrong
